### ISSUE TITLE
Item lists won't save

### ISSUE THREAD

**Issue by meatFlaps** [PTYB/SlayerIssueTracker#85]
Issue: items added to "items to ignore" and "items to alch" list will not stay when saved - seemingly only specific items
Current behavior: not saving therefore not being followed in game
Expected behavior: picking up unwanted items/not alching items selected to alch
Screenshots/Video:
Additional information: a lot of items are fine, but some specific items that won't stay added on the "items to ignore" list are Steel Battleaxe, Steel Platelegs, Steel 2h, etc. Some items for "items to alch" include Rune Full Helm, Rune Battleaxe, etc etc. a lot of items added DID stay, but a lot won't

**Comment by meatFlaps** [comment]
this is causing issues where it will quite frequently eat a piece of food to make room for something insignificant like a steel med helm or a black longsword

**Comment by PTYB** [comment]
Should be fixed in latest version, let me know if theres any issues @meatFlaps

**Comment by meatFlaps** [comment]
> Should be fixed in latest version, let me know if theres any issues @meatFlaps

i hate to be the bearer of bad news but it is not fixed  : (

is there a chance i simply have too many items on my ignore list?

**Comment by PTYB** [comment]
Fixed as per discord conversation
